# Generated by Django 2.1.5 on 2019-11-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16, verbose_name='名前')),
                ('last_name', models.CharField(max_length=16, verbose_name='苗字')),
                ('first_name_reading', models.CharField(max_length=32, verbose_name='名前フリガナ')),
                ('last_name_reading', models.CharField(max_length=32, verbose_name='苗字フリガナ')),
                ('birthday', models.DateField(verbose_name='生年月日')),
                ('gender', models.BooleanField(verbose_name='性別')),
                ('phone_number', models.CharField(max_length=11, verbose_name='電話番号')),
                ('postal_code', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=128)),
                ('job', models.BooleanField()),
                ('highschool_id', models.UUIDField()),
            ],
        ),
    ]
