# Generated by Django 2.1.5 on 2019-11-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50, verbose_name='学科名')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
