# Generated by Django 2.1.5 on 2019-12-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_campus', '0002_auto_20191208_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanthistory',
            name='join_day',
            field=models.CharField(default='nulpo', max_length=15, verbose_name='参加日'),
        ),
    ]
