# Generated by Django 2.1.5 on 2019-12-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_campus', '0002_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='school',
            new_name='school_name',
        ),
    ]
