# Generated by Django 2.1.5 on 2019-12-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_campus', '0003_auto_20191201_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_subject', models.IntegerField(verbose_name='参加学科')),
                ('articipant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_campus.Participant', verbose_name='参加者')),
            ],
            options={
                'db_table': 'participant_history',
            },
        ),
    ]
