# Generated by Django 2.1.5 on 2019-12-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_campus', '0003_participanthistory_join_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participanthistory',
            old_name='articipant',
            new_name='participant',
        ),
    ]
