# Generated by Django 2.1.5 on 2019-12-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_campus', '0004_participanthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanthistory',
            name='join_subject',
            field=models.CharField(max_length=50, verbose_name='参加学科'),
        ),
    ]
