# Generated by Django 2.1.5 on 2019-12-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_campus', '0004_auto_20191208_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanthistory',
            name='school_year',
            field=models.CharField(default='nulpo', max_length=10, verbose_name='学年'),
        ),
    ]
