# Generated by Django 2.1.5 on 2019-12-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_campus', '0005_auto_20191201_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='school_year',
            field=models.CharField(max_length=10, null=True, verbose_name='学年'),
        ),
    ]
