# Generated by Django 2.1.5 on 2019-12-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_campus', '0007_auto_20191203_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='graduate_qualification',
            field=models.NullBooleanField(verbose_name='高認取得済み'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='graduated_check',
            field=models.NullBooleanField(verbose_name='高校卒業済み'),
        ),
    ]
